# infrastructure/plausible/docker-compose.yml
services:
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1
    container_name: alecia-plausible
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    env_file:
      - plausible-conf.env
    volumes:
      - ./custom_head.html:/app/lib/plausible_web/templates/layout/custom_head.html
    ports:
      - "8000:8000"
    depends_on:
      - plausible-db
      - plausible-events-db

  plausible-db:
    image: postgres:16-alpine
    container_name: alecia-plausible-db
    restart: unless-stopped
    volumes:
      - plausible_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PLAUSIBLE_PG_PASSWORD}

  plausible-events-db:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: alecia-plausible-clickhouse
    restart: unless-stopped
    volumes:
      - plausible_events_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  plausible_db_data:
  plausible_events_data:
